/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UserObjectivesDialog.java
 *
 * Created on 11 août 2011, 17:22:08
 */
package VisualAssistantFDM.ui;

import java.util.ArrayList;
import java.util.Enumeration;
import java.util.List;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;

/**
 *
 * @author Abdelheq
 */
public class UserObjectivesDialog extends javax.swing.JDialog {

    private List<Double> fixedUserObjectivesWeight;
    private String visualDimension;
    private String visualCategory;
    
    /** Creates new form UserObjectivesDialog */
    public UserObjectivesDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton10 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        SaveObjectivesButton = new javax.swing.JButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton13 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton18 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton22 = new javax.swing.JRadioButton();
        jRadioButton20 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton24 = new javax.swing.JRadioButton();
        jRadioButton19 = new javax.swing.JRadioButton();
        jRadioButton16 = new javax.swing.JRadioButton();
        jRadioButton17 = new javax.swing.JRadioButton();
        jRadioButton23 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton21 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        visualDimensionComboBox = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        visualCategoryComboBox = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("User objectives Specification"));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setActionCommand("0.33");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setActionCommand("0.66");

        buttonGroup3.add(jRadioButton12);
        jRadioButton12.setSelected(true);
        jRadioButton12.setActionCommand("1");

        buttonGroup2.add(jRadioButton7);
        jRadioButton7.setActionCommand("0.66");

        jLabel6.setText("Suivi et localisation d'informations");

        jLabel3.setText("Pré-analyser des données");

        buttonGroup3.add(jRadioButton10);
        jRadioButton10.setActionCommand("0.33");

        jLabel4.setText("Détecter des frontières");

        SaveObjectivesButton.setText("Save user objectives specifications");
        SaveObjectivesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveObjectivesButtonActionPerformed(evt);
            }
        });

        buttonGroup4.add(jRadioButton14);
        jRadioButton14.setActionCommand("0.33");

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setSelected(true);
        jRadioButton4.setActionCommand("1");

        buttonGroup2.add(jRadioButton5);
        jRadioButton5.setActionCommand("0");

        buttonGroup2.add(jRadioButton6);
        jRadioButton6.setActionCommand("0.33");

        buttonGroup4.add(jRadioButton13);
        jRadioButton13.setActionCommand("0");

        jLabel5.setText("Estimation");

        buttonGroup4.add(jRadioButton15);
        jRadioButton15.setActionCommand("0.66");

        buttonGroup5.add(jRadioButton18);
        jRadioButton18.setActionCommand("0.33");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setActionCommand("0");

        buttonGroup6.add(jRadioButton22);
        jRadioButton22.setActionCommand("0.66");

        buttonGroup5.add(jRadioButton20);
        jRadioButton20.setSelected(true);
        jRadioButton20.setActionCommand("1");

        buttonGroup3.add(jRadioButton9);
        jRadioButton9.setActionCommand("0");

        buttonGroup2.add(jRadioButton8);
        jRadioButton8.setSelected(true);
        jRadioButton8.setActionCommand("1");

        buttonGroup3.add(jRadioButton11);
        jRadioButton11.setActionCommand("0.66");

        buttonGroup6.add(jRadioButton24);
        jRadioButton24.setActionCommand("0");

        buttonGroup5.add(jRadioButton19);
        jRadioButton19.setActionCommand("0.66");

        buttonGroup4.add(jRadioButton16);
        jRadioButton16.setSelected(true);
        jRadioButton16.setActionCommand("1");

        buttonGroup5.add(jRadioButton17);
        jRadioButton17.setActionCommand("0");

        buttonGroup6.add(jRadioButton23);
        jRadioButton23.setActionCommand("0.33");

        jLabel1.setText("Recherche d'informations");

        jLabel2.setText("Voir l'ensemble des données");

        buttonGroup6.add(jRadioButton21);
        jRadioButton21.setSelected(true);
        jRadioButton21.setActionCommand("1");

        jLabel7.setText("Aucune importance");

        jLabel8.setText("Faible importance");

        jLabel9.setText("Moyenne importance");

        jLabel10.setText("Forte importance");

        jLabel11.setText("Visual dimension");

        visualDimensionComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1 Dimension", "2 Dimension", "3 Dimension" }));

        jLabel12.setText("Visual Category");

        visualCategoryComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Spatial", "Temporal", "Relational", "Hierarchical" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(34, 34, 34))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(34, 34, 34))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(34, 34, 34))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(34, 34, 34)))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel7)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton5)
                            .addComponent(jRadioButton9)
                            .addComponent(jRadioButton13)
                            .addComponent(jRadioButton17)
                            .addComponent(jRadioButton24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton6)
                            .addComponent(jRadioButton10)
                            .addComponent(jRadioButton14)
                            .addComponent(jRadioButton18)
                            .addComponent(jRadioButton23)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jRadioButton22)
                            .addComponent(jRadioButton19)
                            .addComponent(jRadioButton15)
                            .addComponent(jRadioButton11)
                            .addComponent(jRadioButton7)
                            .addComponent(jRadioButton3)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jRadioButton4)
                            .addComponent(jRadioButton8)
                            .addComponent(jRadioButton12)
                            .addComponent(jRadioButton16)
                            .addComponent(jRadioButton20)
                            .addComponent(jRadioButton21)
                            .addComponent(jLabel10))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(SaveObjectivesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(277, 277, 277))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(335, 335, 335)
                                .addComponent(jLabel12))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(visualDimensionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(171, 171, 171)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(visualCategoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(213, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(visualDimensionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(visualCategoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton6)
                    .addComponent(jRadioButton7)
                    .addComponent(jRadioButton8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(jRadioButton9)
                    .addComponent(jRadioButton10)
                    .addComponent(jRadioButton11)
                    .addComponent(jRadioButton12))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4)
                    .addComponent(jRadioButton13)
                    .addComponent(jRadioButton14)
                    .addComponent(jRadioButton15)
                    .addComponent(jRadioButton16))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel5)
                    .addComponent(jRadioButton17)
                    .addComponent(jRadioButton18)
                    .addComponent(jRadioButton19)
                    .addComponent(jRadioButton20))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel6)
                    .addComponent(jRadioButton21)
                    .addComponent(jRadioButton24)
                    .addComponent(jRadioButton23)
                    .addComponent(jRadioButton22))
                .addGap(18, 18, 18)
                .addComponent(SaveObjectivesButton)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void SaveObjectivesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveObjectivesButtonActionPerformed
        
        fixedUserObjectivesWeight = new ArrayList<Double>();
        fixedUserObjectivesWeight.add(getSelectedButton(buttonGroup1));
        fixedUserObjectivesWeight.add(getSelectedButton(buttonGroup2));
        fixedUserObjectivesWeight.add(getSelectedButton(buttonGroup3));
        fixedUserObjectivesWeight.add(getSelectedButton(buttonGroup4));
        fixedUserObjectivesWeight.add(getSelectedButton(buttonGroup5));
        fixedUserObjectivesWeight.add(getSelectedButton(buttonGroup6));
        this.setVisible(false);        
}//GEN-LAST:event_SaveObjectivesButtonActionPerformed

   public Double getSelectedButton(ButtonGroup group) {
    Enumeration<AbstractButton> e = group.getElements();
        while (e.hasMoreElements()) {
           AbstractButton b =  e.nextElement();
           if (b.isSelected()) return  Double.valueOf(b.getActionCommand());
        }
        return null;
   }
   
   public List<Double> getUserObjectivesVector(){
        return this.fixedUserObjectivesWeight;
    }
   
    /**
     * @return the visualDimension
     */
    public String getVisualDimension() {
        visualDimension = visualDimensionComboBox.getSelectedItem().toString();
        return visualDimension;
    }

    /**
     * @param visualDimension the visualDimension to set
     */
    public void setVisualDimension(String visualDimension) {
        this.visualDimension = visualDimension;
    }

    /**
     * @return the visualCategory
     */
    public String getVisualCategory() {
        visualCategory = visualCategoryComboBox.getSelectedItem().toString(); 
        return visualCategory;
    }

    /**
     * @param visualCategory the visualCategory to set
     */
    public void setVisualCategory(String visualCategory) {
        this.visualCategory = visualCategory;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
   

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                UserObjectivesDialog dialog = new UserObjectivesDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SaveObjectivesButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton17;
    private javax.swing.JRadioButton jRadioButton18;
    private javax.swing.JRadioButton jRadioButton19;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton20;
    private javax.swing.JRadioButton jRadioButton21;
    private javax.swing.JRadioButton jRadioButton22;
    private javax.swing.JRadioButton jRadioButton23;
    private javax.swing.JRadioButton jRadioButton24;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JComboBox visualCategoryComboBox;
    private javax.swing.JComboBox visualDimensionComboBox;
    // End of variables declaration//GEN-END:variables
}
