/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VisualizationForm.java
 *
 * Created on 6 janv. 2011, 22:53:55
 */

package VisualAssistantFDM.ui;

import java.util.logging.Level;
import java.util.logging.Logger;
import visualisation3d.vrmNuage3D.Visualisation_Nuage_3D;
import vrminerlib.core.VRMinerFramework;

/**
 *
 * @author Abdelheq
 */
public class VisualizationForm extends javax.swing.JFrame {

    private Visualisation_Nuage_3D visu3D;
    private String XMLFilePath;

    /**
     * Generate saved visualizations .
     * @param path PathofFile.
     * @param profilNumber ProfilNumber.
     */
    public VisualizationForm(String path, int profilNumber) throws Exception{
        XMLFilePath = path;
        initComponents();
        VRMinerFramework.resetFramework();
        

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OverView3DVisualization = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        OverView3DVisualization.setPreferredSize(new java.awt.Dimension(400, 400));
        getContentPane().add(OverView3DVisualization, java.awt.BorderLayout.CENTER);
        visu3D = new Visualisation_Nuage_3D(0, 0, 0);
        visu3D.ConfigurationNuage3D(XMLFilePath, "profil"+0);
        visu3D.createScene();
        OverView3DVisualization.setViewportView(visu3D.getCustomCanvas3D());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
//    public static void main(String args[]) throws Exception{
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                String path = "C:\\Users\\Abdelheq\\Desktop\\IRIS.xml";
//                try {
//                    new VisualizationForm(path).setVisible(true);
//                } catch (Exception ex) {
//                    Logger.getLogger(VisualizationForm.class.getName()).log(Level.SEVERE, null, ex);
//                }
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane OverView3DVisualization;
    // End of variables declaration//GEN-END:variables

}
