/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VisualizationsList.java
 *
 * Created on 14 juin 2011, 16:58:17
 */

package com.mycompany.visualassistantfacv;

import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import visualisation3d.vrmNuage3D.Visualisation_Nuage_3D;

/**
 *
 * @author Abdelheq
 */
public class VisualizationsList extends javax.swing.JFrame {

    /** Creates new form VisualizationsList */
    public VisualizationsList() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jToolBar1 = new javax.swing.JToolBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane2.setAutoscrolls(true);

        jToolBar1.setRollover(true);
        jScrollPane2.setViewportView(jToolBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 908, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisualizationsList().setVisible(true);
                
                for(int i=1; i<=5; i++){
                jScrollPane = new JScrollPane();
                jScrollPane.setPreferredSize(new java.awt.Dimension(320, 30));
                JSeparator = new JSeparator();
                jToolBar1.add(jScrollPane);
                jToolBar1.add(JSeparator);
                Visualisation_Nuage_3D visu3D1 = new Visualisation_Nuage_3D(0, 0, 0);
                visu3D1.ConfigurationNuage3D(XMLFilepath, "profil"+i);
                visu3D1.createScene();
                jScrollPane.setViewportView(visu3D1.getCustomCanvas3D());
                
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private static javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
private static JScrollPane jScrollPane;
private static JSeparator JSeparator;
private static String XMLFilepath = "C:\\Users\\Abdelheq\\Desktop\\Base de données de tests\\CD\\listeCD.xml";
}
