/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ClusteringPanel.java
 *
 * Created on 13 janv. 2011, 16:11:55
 */

package visualassistantfacv;

import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author Abdelheq
 */
public class ClusteringPanel extends javax.swing.JPanel {

    /** Creates new form ClusteringPanel */
    public ClusteringPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Clusturing = new javax.swing.JCheckBox();
        ClustVisib = new javax.swing.JCheckBox();
        EclairageSphere = new javax.swing.JCheckBox();
        jLabelClust = new javax.swing.JLabel();
        attClustLabel = new javax.swing.JLabel();
        attClust = new javax.swing.JComboBox();
        clustMethodeLabel = new javax.swing.JLabel();
        clustMethode = new javax.swing.JComboBox();
        clustObjetLabel = new javax.swing.JLabel();
        clustObjet = new javax.swing.JComboBox();
        objSize3 = new javax.swing.JSlider();
        clustFact = new javax.swing.JSlider();
        objSize3Label = new javax.swing.JLabel();
        clustFactLabel = new javax.swing.JLabel();
        size3 = new javax.swing.JLabel();
        ToggleButton = new javax.swing.JButton();
        slideClust = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Clusturing.setText("Activer Clustering");
        Clusturing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClusturingActionPerformed(evt);
            }
        });
        add(Clusturing, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 183, -1));

        ClustVisib.setText("Visibilite Objets");
        add(ClustVisib, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 43, -1, -1));

        EclairageSphere.setText("Spheres eclairees");
        EclairageSphere.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                EclairageSphereItemStateChanged(evt);
            }
        });
        add(EclairageSphere, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 68, -1, -1));

        jLabelClust.setIcon(new javax.swing.ImageIcon("C:\\Users\\Abdelheq\\Desktop\\VRMiner\\trunk\\Nuage3d\\src\\images\\Clusturing.PNG")); // NOI18N
        jLabelClust.setText("Placer l'icone ici");
        add(jLabelClust, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 13, 170, 134));

        attClustLabel.setText("Attribut classe :");
        add(attClustLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 102, 198, -1));

        attClust.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(attClust, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 125, 164, -1));

        clustMethodeLabel.setText("Methodes :");
        add(clustMethodeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 165, 143, -1));

        clustMethode.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        clustMethode.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                clustMethodeItemStateChanged(evt);
            }
        });
        add(clustMethode, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 188, 163, -1));

        clustObjetLabel.setText("Objets Liaisons");
        add(clustObjetLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 223, 143, -1));

        clustObjet.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        clustObjet.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                clustObjetItemStateChanged(evt);
            }
        });
        add(clustObjet, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 246, 160, -1));

        objSize3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                objSize3StateChanged(evt);
            }
        });
        add(objSize3, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 188, 135, -1));

        clustFact.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                clustFactStateChanged(evt);
            }
        });
        add(clustFact, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 245, 135, -1));

        objSize3Label.setText("Pourcentage Transparence :");
        add(objSize3Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 165, -1, -1));

        clustFactLabel.setText("Echelle Rayon Sphères : ");
        add(clustFactLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 222, -1, -1));

        size3.setText("0%");
        add(size3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 156, 20, 30));

        ToggleButton.setText("Reset");
        ToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToggleButtonActionPerformed(evt);
            }
        });
        add(ToggleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 275, -1, -1));

        slideClust.setText("1");
        add(slideClust, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void ClusturingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClusturingActionPerformed
       
    if (!Clusturing.isSelected()) {
        ClustVisib.setEnabled(false);
        attClust.setEnabled(false);
        clustMethode.setEnabled(false);
        clustFact.setEnabled(false);
        objSize3.setEnabled(false);
        size3.setEnabled(false);
        EclairageSphere.setEnabled(false);
        ToggleButton.setEnabled(false);


    } else {
        ClustVisib.setEnabled(true);
        attClust.setEnabled(true);
        clustMethode.setEnabled(true);
        clustFact.setEnabled(true);
        objSize3.setEnabled(true);
        size3.setEnabled(true);
        EclairageSphere.setEnabled(true);
        ToggleButton.setEnabled(true);
        if (EclairageSphere.isSelected()) {
            objSize3.setEnabled(false);
            ClustVisib.setEnabled(false);
        } else {
            objSize3.setEnabled(true);
            ClustVisib.setEnabled(true);
        }

    }

    }//GEN-LAST:event_ClusturingActionPerformed

    private void EclairageSphereItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_EclairageSphereItemStateChanged
        if (EclairageSphere.isSelected()) {
        objSize3.setEnabled(false);
        ClustVisib.setEnabled(false);
    } else {
        objSize3.setEnabled(true);
        ClustVisib.setEnabled(true);
    }
    }//GEN-LAST:event_EclairageSphereItemStateChanged

    private void clustMethodeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_clustMethodeItemStateChanged
        if (clustMethode.getSelectedIndex() == 1) {
        clustObjet.setEnabled(true);
    } else {
        clustObjet.setEnabled(false);
    }

    //testImagesClust();

    }//GEN-LAST:event_clustMethodeItemStateChanged

    private void clustObjetItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_clustObjetItemStateChanged
    ClassLoader cldr = this.getClass().getClassLoader();
    if (clustMethode.getSelectedIndex() == 1 && clustObjet.getSelectedIndex() == 0) {

        BufferedImage im = null;
        ImageIcon imageIconClust = new ImageIcon();
        try {
            im = ImageIO.read(getClass().getResourceAsStream("/images/PPV_base_chanel_sphere.PNG"));
            im = (BufferedImage) scale(im, 138, 98);
        } catch (Exception e) {
        }
        imageIconClust.setImage(im);
        jLabelClust.setIcon(imageIconClust);
    } else if (clustMethode.getSelectedIndex() == 1 && clustObjet.getSelectedIndex() == 1) {

        BufferedImage im = null;
        ImageIcon imageIconClust = new ImageIcon();
        try {
            im = ImageIO.read(getClass().getResourceAsStream("/images/PPV_base_chanel_tube.PNG"));
            im = (BufferedImage) scale(im, 138, 98);
        } catch (Exception e) {
        }
        imageIconClust.setImage(im);
        jLabelClust.setIcon(imageIconClust);
    }
    }//GEN-LAST:event_clustObjetItemStateChanged

    private void objSize3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_objSize3StateChanged
        size3.setText("" + objSize3.getValue() + "%");
    }//GEN-LAST:event_objSize3StateChanged

    private void ToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToggleButtonActionPerformed
        if (clustMethode.getSelectedIndex() == 1) {
        clustObjet.setEnabled(true);
    } else {
        clustObjet.setEnabled(false);
    }

    //testImagesClust();
    }//GEN-LAST:event_ToggleButtonActionPerformed

    private void clustFactStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_clustFactStateChanged
        float val = clustFact.getValue();
        if (val != 0.0f) {
            val = val / 100f;
        }

        slideClust.setText(String.valueOf(val));
    }//GEN-LAST:event_clustFactStateChanged

    private static Image scale(Image source, int width, int height) {
        BufferedImage buf = new BufferedImage(width, height, BufferedImage.TYPE_INT_ARGB);
        Graphics2D g = buf.createGraphics();
        g.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
        g.drawImage(source, 0, 0, width, height, null);
        g.dispose();
        return buf;
    }

    public String getAttClust() {
        return (String) attClust.getSelectedItem();
    }

    public String getClusturing() {
        if (Clusturing.isSelected()) {
            return "true";
        } else {
            return "false";
        }
    }

    public String getClustVisib() {
        if (ClustVisib.isSelected()) {
            return "true";
        } else {
            return "false";
        }
    }

    public String getEclairageSphere() {
        if (EclairageSphere.isSelected()) {
            return "true";
        } else {
            return "false";
        }
    }

    public String getclustMethode() {
        return String.valueOf(clustMethode.getSelectedIndex());
    }

    public String getclustObjet() {
        return String.valueOf(clustObjet.getSelectedIndex());
    }

    public String getclustFact() {
        return String.valueOf(clustFact.getValue());
    }

    public String getobjSize3() {
        return String.valueOf(objSize3.getValue());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ClustVisib;
    private javax.swing.JCheckBox Clusturing;
    private javax.swing.JCheckBox EclairageSphere;
    private javax.swing.JButton ToggleButton;
    private javax.swing.JComboBox attClust;
    private javax.swing.JLabel attClustLabel;
    private javax.swing.JSlider clustFact;
    private javax.swing.JLabel clustFactLabel;
    private javax.swing.JComboBox clustMethode;
    private javax.swing.JLabel clustMethodeLabel;
    private javax.swing.JComboBox clustObjet;
    private javax.swing.JLabel clustObjetLabel;
    private javax.swing.JLabel jLabelClust;
    private javax.swing.JSlider objSize3;
    private javax.swing.JLabel objSize3Label;
    private javax.swing.JLabel size3;
    private javax.swing.JLabel slideClust;
    // End of variables declaration//GEN-END:variables

}
