/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Espace3DPanel.java
 *
 * Created on 13 janv. 2011, 16:12:11
 */

package VisualAssistantFDM.configuration;

import java.awt.Color;
import java.text.DecimalFormat;
import javax.swing.JColorChooser;

/**
 *
 * @author Abdelheq
 */
public class Espace3DPanel extends javax.swing.JPanel {

    private float ValEcartYeux = 0.0035f;
    private Color backGroundColor;
    private Color ChoixCouleur5 = null;
    private boolean terrain = false;
    private boolean bgrid;

    /** Creates new form Espace3DPanel */
    public Espace3DPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxStereo = new javax.swing.JCheckBox();
        SliderYeuxLabel = new javax.swing.JLabel();
        size1 = new javax.swing.JLabel();
        size1Label = new javax.swing.JLabel();
        TailleLabel = new javax.swing.JLabel();
        TextFieldTaille = new javax.swing.JTextField();
        SliderYeux = new javax.swing.JSlider();
        TailleLabel1 = new javax.swing.JLabel();
        DistanceLabel = new javax.swing.JLabel();
        TextFieldDistance = new javax.swing.JTextField();
        DistanceLabel1 = new javax.swing.JLabel();
        grilleTerrain = new javax.swing.JCheckBox();
        popUpInfo = new javax.swing.JCheckBox();
        bkgdColorViewLabel = new javax.swing.JLabel();
        bkgdColorView = new javax.swing.JTextField();
        bkgdColorViewbtn = new javax.swing.JButton();
        Color5 = new javax.swing.JTextField();
        Color5btn = new javax.swing.JButton();
        Color5Label = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        objSize2 = new javax.swing.JSlider();
        size2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCheckBoxStereo.setText("Activer Stereoscopie");
        jCheckBoxStereo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxStereoActionPerformed(evt);
            }
        });
        add(jCheckBoxStereo, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 9, -1, -1));

        SliderYeuxLabel.setText("Ecartement des yeux");
        add(SliderYeuxLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 13, -1, -1));

        size1.setText("0.0000X");
        add(size1, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 13, -1, -1));

        size1Label.setText("m");
        add(size1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 13, -1, -1));

        TailleLabel.setText("Votre taille :");
        add(TailleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 58, -1, -1));

        TextFieldTaille.setText("1.70");
        add(TextFieldTaille, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 52, -1, -1));

        SliderYeux.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SliderYeuxStateChanged(evt);
            }
        });
        add(SliderYeux, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 36, 181, -1));

        TailleLabel1.setText("m");
        add(TailleLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 58, -1, -1));

        DistanceLabel.setText("Distance Projecteur - Ecran :");
        add(DistanceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 98, -1, -1));

        TextFieldDistance.setText(" 2");
        TextFieldDistance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldDistanceActionPerformed(evt);
            }
        });
        add(TextFieldDistance, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 92, 24, -1));

        DistanceLabel1.setText("m");
        add(DistanceLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 98, -1, -1));

        grilleTerrain.setText("Afficher grille terrain");
        add(grilleTerrain, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 123, -1, -1));

        popUpInfo.setText("Pop up d'Informations");
        add(popUpInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 153, -1, -1));

        bkgdColorViewLabel.setText("Couleur de fond");
        add(bkgdColorViewLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 162, -1, -1));

        bkgdColorView.setBackground(new java.awt.Color(153, 153, 153));
        add(bkgdColorView, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 185, 52, 25));

        bkgdColorViewbtn.setText("...");
        bkgdColorViewbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkgdColorViewbtnActionPerformed(evt);
            }
        });
        add(bkgdColorViewbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 185, 52, -1));

        Color5.setBackground(new java.awt.Color(204, 0, 0));
        add(Color5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 245, 52, 25));

        Color5btn.setText("...");
        Color5btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Color5btnActionPerformed(evt);
            }
        });
        add(Color5btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 245, 52, -1));

        Color5Label.setText("Couleur du cube englobant");
        add(Color5Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 222, -1, -1));

        jLabel10.setText("Pourcentage de la transparence :");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 222, -1, -1));

        objSize2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                objSize2StateChanged(evt);
            }
        });
        add(objSize2, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 245, 142, -1));

        size2.setText("90");
        add(size2, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 245, -1, -1));

        jLabel12.setText("%");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 245, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldDistanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldDistanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldDistanceActionPerformed

    private void jCheckBoxStereoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxStereoActionPerformed
        if (jCheckBoxStereo.isSelected()) {
        SliderYeux.setValue(50);
        } else {
            SliderYeux.setValue(0);
        }
    }//GEN-LAST:event_jCheckBoxStereoActionPerformed

    private void SliderYeuxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SliderYeuxStateChanged
        float ValTrans = (float) 0.00007;
        float valTemp = SliderYeux.getValue() * ValTrans;
        setValTemp(valTemp);

        DecimalFormat df = new DecimalFormat("########.00000");
        size1.setText("" + (df.format(valTemp)));

        setValTemp(valTemp);
    }//GEN-LAST:event_SliderYeuxStateChanged

    private void bkgdColorViewbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkgdColorViewbtnActionPerformed
        backGroundColor = JColorChooser.showDialog(
            this,
            "Couleur du fond",
            Color.GRAY);
        bkgdColorView.setBackground(backGroundColor);
    }//GEN-LAST:event_bkgdColorViewbtnActionPerformed

    private void Color5btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Color5btnActionPerformed
        Color col = Color5.getBackground();

        Color color1 = JColorChooser.showDialog(
                this,
                "Couleur du pyramdian du haut",
                col);
        Color5.setBackground(color1);

        ChoixCouleur5 = color1;
    }//GEN-LAST:event_Color5btnActionPerformed

    private void objSize2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_objSize2StateChanged
        size2.setText("" + objSize2.getValue() + "%");
    }//GEN-LAST:event_objSize2StateChanged

    public void setValTemp(float valTemp) {
        ValEcartYeux = valTemp;
    }

    public String getColor5() {
        return String.valueOf(Color5.getBackground().getRGB());
    }

    public String getObjSize2() {
        return String.valueOf(objSize2.getValue());
    }

    public String getGrilleTerrain() {
        if (grilleTerrain.isSelected()) {
            return "true";
        } else {
            return "false";
        }
    }

    public String getBkgdColorView() {
        return "" + bkgdColorView.getBackground().getRGB();
    }

    public String getjCheckBoxStereo() {
        if (jCheckBoxStereo.isSelected()) {
            return "true";
        } else {
            return "false";
        }
    }

    public String getjSliderYeux() {
        return String.valueOf(SliderYeux.getValue());
    }

    public String getjTextFieldTaille() {
        return TextFieldTaille.getText();
    }

    public String getjTextFieldDistance() {
        return TextFieldDistance.getText();
    }

    public String getpopUpInfo() {
        if (popUpInfo.isSelected()) {
            return "true";
        } else {
            return "false";
        }
    }

    public boolean getTerrain() {
        return terrain;
    }

    public void setTerrain(boolean _terrain) {
        terrain = _terrain;
    }

    public float EcartementYeux() {
        return ValEcartYeux;
    }

    public void setGrid(boolean _bgrid) {
        bgrid = _bgrid;
    }

    public boolean getGrid() {
        return bgrid;
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Color5;
    private javax.swing.JLabel Color5Label;
    private javax.swing.JButton Color5btn;
    private javax.swing.JLabel DistanceLabel;
    private javax.swing.JLabel DistanceLabel1;
    private javax.swing.JSlider SliderYeux;
    private javax.swing.JLabel SliderYeuxLabel;
    private javax.swing.JLabel TailleLabel;
    private javax.swing.JLabel TailleLabel1;
    private javax.swing.JTextField TextFieldDistance;
    private javax.swing.JTextField TextFieldTaille;
    private javax.swing.JTextField bkgdColorView;
    private javax.swing.JLabel bkgdColorViewLabel;
    private javax.swing.JButton bkgdColorViewbtn;
    private javax.swing.JCheckBox grilleTerrain;
    private javax.swing.JCheckBox jCheckBoxStereo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JSlider objSize2;
    private javax.swing.JCheckBox popUpInfo;
    private javax.swing.JLabel size1;
    private javax.swing.JLabel size1Label;
    private javax.swing.JLabel size2;
    // End of variables declaration//GEN-END:variables

}
