/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VisualAssistant_test.java
 *
 * Created on 16 déc. 2010, 14:12:17
 */

package visualassistantfacv;

import java.awt.event.MouseEvent;
import visualisation3d.vrmNuage3D.Visualisation_Nuage_3D;
import vrminerlib.core.VRMinerFramework;
import vrminerlib.object3d.Object3D;
import vrminerlib.scene.PointOfView;
import vrminerlib.scene.PointOfViewMouseAdapter;


/**
 *
 * @author Abdelheq
 */
public class VisualAssistant_test extends javax.swing.JFrame {

    /** Creates new form VisualAssistant_test */
    public VisualAssistant_test() {
        VRMinerFramework.initializeFramework();
        initComponents();
//        Visualisation_Nuage_3D visu3D1 = new Visualisation_Nuage_3D(panel1, 0, 0, 0);
//        //Visualisation_Nuage_3D visu3D2 = new Visualisation_Nuage_3D(panel2, 0, 0, 0);
////            Visualisation_Nuage_3D visu3D1 = new Visualisation_Nuage_3D(panel2, 0, 0, 0);
////            Visualisation_Nuage_3D visu3D2 = new Visualisation_Nuage_3D(panel3, 0, 0, 0);
//        visu3D1.ConfigurationNuage3D("C:\\Users\\Abdelheq\\Desktop\\IRIS.xml", "profil"+1);
//       // visu3D2.ConfigurationNuage3D("C:\\Users\\Abdelheq\\Desktop\\IRIS.xml", "profil"+1);
//
////            visu3D1.ConfigurationNuage3D("C:\\Users\\Abdelheq\\Desktop\\IRIS.xml", "profil"+1);
////            visu3D2.ConfigurationNuage3D("C:\\Users\\Abdelheq\\Desktop\\IRIS.xml", "profil"+1);
////            panel1.add(new Visualisation_Nuage_3D(panel1, 0, 0, 0));
//////            panel1.add(new ColorCube3D());
//////            panel1.add(new ColorCube3D());
////            myJFrame.add(panel1, BorderLayout.NORTH);
////            myJFrame.add(panel2, BorderLayout.CENTER);
////            myJFrame.add(panel3, BorderLayout.SOUTH);
//        visu3D1.createScene();
//        //visu3D2.createScene();
////            visu3D1.createScene();
////            visu3D2.createScene();
////        myJFrame.setSize(1200, 800);
////        myJFrame.setVisible(true);
//        //}
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollpane1 = new javax.swing.JScrollPane();
        scrollpane2 = new javax.swing.JScrollPane();
        scrollpane3 = new javax.swing.JScrollPane();
        scrollpane4 = new javax.swing.JScrollPane();
        scrollpane5 = new javax.swing.JScrollPane();
        scrollpane6 = new javax.swing.JScrollPane();
        scrollpane7 = new javax.swing.JScrollPane();
        scrollpane8 = new javax.swing.JScrollPane();
        scrollpane9 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Visual Assistant");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scrollpane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrollpane2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrollpane8, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrollpane7, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(scrollpane3, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(scrollpane4, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(scrollpane5, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(scrollpane6, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrollpane9, javax.swing.GroupLayout.DEFAULT_SIZE, 731, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {scrollpane3, scrollpane4});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {scrollpane1, scrollpane2, scrollpane5, scrollpane6, scrollpane7, scrollpane8});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(scrollpane2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(scrollpane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(scrollpane7, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(scrollpane8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(scrollpane4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollpane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(scrollpane6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollpane5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)))
                    .addComponent(scrollpane9, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {scrollpane1, scrollpane2, scrollpane3, scrollpane4, scrollpane5, scrollpane6, scrollpane7, scrollpane8});

        Visualisation_Nuage_3D visu3D = new Visualisation_Nuage_3D(0, 0, 0);
        visu3D.ConfigurationNuage3D("C:\\Users\\Abdelheq\\Desktop\\IRIS.xml", "profil"+1);
        visu3D.createScene();
        scrollpane1.setViewportView(visu3D.getCustomCanvas3D());
        visu3D.addPointOfViewListener(visu3D.getMainPointOfView().getName(), new PointOfViewMouseAdapter() {

            @Override
            public void onMouseLeftClick(MouseEvent m, PointOfView p, Object3D o){

                updatePreview(1);//afficher le profil i : qui est passé en paramètre

            }
        });
        Visualisation_Nuage_3D visu3D1 = new Visualisation_Nuage_3D(0, 0, 0);
        visu3D1.ConfigurationNuage3D("C:\\Users\\Abdelheq\\Desktop\\IRIS.xml", "profil"+2);
        visu3D1.createScene();
        scrollpane2.setViewportView(visu3D1.getCustomCanvas3D());
        visu3D1.addPointOfViewListener(visu3D1.getMainPointOfView().getName(), new PointOfViewMouseAdapter() {

            @Override
            public void onMouseLeftClick(MouseEvent m, PointOfView p, Object3D o){

                updatePreview(2);

            }
        });
        Visualisation_Nuage_3D visu3D3 = new Visualisation_Nuage_3D(0, 0, 0);
        visu3D3.ConfigurationNuage3D("C:\\Users\\Abdelheq\\Desktop\\IRIS.xml", "profil"+5);
        visu3D3.createScene();
        scrollpane3.setViewportView(visu3D3.getCustomCanvas3D());
        visu3D3.addPointOfViewListener(visu3D3.getMainPointOfView().getName(), new PointOfViewMouseAdapter() {

            @Override
            public void onMouseLeftClick(MouseEvent m, PointOfView p, Object3D o){

                updatePreview(3);

            }
        });
        Visualisation_Nuage_3D visu3D4 = new Visualisation_Nuage_3D(0, 0, 0);
        visu3D4.ConfigurationNuage3D("C:\\Users\\Abdelheq\\Desktop\\IRIS.xml", "profil"+3);
        visu3D4.createScene();
        scrollpane4.setViewportView(visu3D4.getCustomCanvas3D());
        visu3D4.addPointOfViewListener(visu3D4.getMainPointOfView().getName(), new PointOfViewMouseAdapter() {

            @Override
            public void onMouseLeftClick(MouseEvent m, PointOfView p, Object3D o){

                updatePreview(3);

            }
        });
        Visualisation_Nuage_3D visu3D5 = new Visualisation_Nuage_3D(0, 0, 0);
        visu3D5.ConfigurationNuage3D("C:\\Users\\Abdelheq\\Desktop\\IRIS.xml", "profil"+1);
        visu3D5.createScene();
        scrollpane5.setViewportView(visu3D5.getCustomCanvas3D());
        visu3D5.addPointOfViewListener(visu3D5.getMainPointOfView().getName(), new PointOfViewMouseAdapter() {

            @Override
            public void onMouseLeftClick(MouseEvent m, PointOfView p, Object3D o){

                updatePreview(5);

            }
        });
        Visualisation_Nuage_3D visu3D6 = new Visualisation_Nuage_3D(0, 0, 0);
        visu3D6.ConfigurationNuage3D("C:\\Users\\Abdelheq\\Desktop\\IRIS.xml", "profil"+1);
        visu3D6.createScene();
        scrollpane6.setViewportView(visu3D6.getCustomCanvas3D());
        visu3D6.addPointOfViewListener(visu3D6.getMainPointOfView().getName(), new PointOfViewMouseAdapter() {

            @Override
            public void onMouseLeftClick(MouseEvent m, PointOfView p, Object3D o){

                updatePreview(6);

            }
        });
        Visualisation_Nuage_3D visu3D7 = new Visualisation_Nuage_3D(0, 0, 0);
        visu3D7.ConfigurationNuage3D("C:\\Users\\Abdelheq\\Desktop\\IRIS.xml", "profil"+4);
        visu3D7.createScene();
        scrollpane7.setViewportView(visu3D7.getCustomCanvas3D());
        visu3D7.addPointOfViewListener(visu3D7.getMainPointOfView().getName(), new PointOfViewMouseAdapter() {

            @Override
            public void onMouseLeftClick(MouseEvent m, PointOfView p, Object3D o){

                updatePreview(7);

            }
        });
        Visualisation_Nuage_3D visu3D8 = new Visualisation_Nuage_3D(0, 0, 0);
        visu3D8.ConfigurationNuage3D("C:\\Users\\Abdelheq\\Desktop\\IRIS.xml", "profil"+3);
        visu3D8.createScene();
        scrollpane8.setViewportView(visu3D8.getCustomCanvas3D());
        visu3D8.addPointOfViewListener(visu3D8.getMainPointOfView().getName(), new PointOfViewMouseAdapter() {

            @Override
            public void onMouseLeftClick(MouseEvent m, PointOfView p, Object3D o){

                updatePreview(8);

            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisualAssistant_test().setVisible(true);
            }
        });
    }

    private void updatePreview(int profil){
        System.out.println("Le numéro du profil est : "+profil);
        Visualisation_Nuage_3D visu3D9 = new Visualisation_Nuage_3D(0, 0, 0);
        visu3D9.ConfigurationNuage3D("C:\\Users\\Abdelheq\\Desktop\\IRIS.xml", "profil"+profil);
        visu3D9.createScene();
        scrollpane9.setViewportView(visu3D9.getCustomCanvas3D());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrollpane1;
    private javax.swing.JScrollPane scrollpane2;
    private javax.swing.JScrollPane scrollpane3;
    private javax.swing.JScrollPane scrollpane4;
    private javax.swing.JScrollPane scrollpane5;
    private javax.swing.JScrollPane scrollpane6;
    private javax.swing.JScrollPane scrollpane7;
    private javax.swing.JScrollPane scrollpane8;
    private javax.swing.JScrollPane scrollpane9;
    // End of variables declaration//GEN-END:variables
    
}
